# https://github.com/ptb/mac-setup/blob/develop/mac-setup.command

cask "valentina-studio"
cask "webex-teams"

tap "heroku/brew"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/core"
tap "homebrew/services"

cask "homebrew/cask-drivers/kiibohd-configurator"
cask "pomotodo"
cask "time-out"
cask "karabiner-elements"
cask "wacom-tablet"
cask "wacom-inkspace"
cask "lulu"

cask "adoptopenjdk"
cask "xquartz"
cask "suspicious-package"
cask "virtualbox"
cask "visualvm"
cask "platypus"
cask "postman"

cask "dash"
cask "mactex"
cask "latexit"
cask "macdown"
cask "gitkraken"
brew "vim"
cask "sublime-text2"
cask "intellij-idea-ce"
cask "visual-studio-code"
cask "android-studio-preview"
cask "homebrew/cask-fonts/font-inconsolata-lgc"
cask "font-firacode-nerd-font-mono"

brew "irssi"
cask "nzbvortex"
cask "transmission"
brew "wireshark"
cask "notion"
cask "skype"
cask "zoomus"
cask "google-hangouts"
cask "discord"
cask "slack"
cask "keybase"

brew "figlet"
brew "brogue"
brew "google-earth-pro"

cask "google-chrome"
cask "chromedriver"
cask "firefox-nightly"
cask "firefox"
cask "safari-technology-preview"
cask "tor-browser"
cask "opera"
cask "brave-browser-nightly"

brew "cocoapods"
brew "duti"
brew "ios-deploy"
brew "ideviceinstaller"
brew "mas"
brew "pinentry-mac"

brew "docker"
brew "docker-compose"
brew "docker-machine"
brew "gdl"
brew "heroku/brew/heroku"
cask "docker"

brew "zsh"
brew "zsh-completions"
brew "zsh-git-prompt"
brew "bash-completion"
brew "bash-git-prompt"
brew "mosh"
brew "bundler-completion"
brew "curl"
brew "curl-openssl"
brew "wget"
brew "jq"
brew "bat"
brew "renameutils"

brew "dnsmasq"
brew "ncdu"
#brew "fasd"
brew "ack"
brew "aspell"
brew "pcre2"
brew "poppler"
brew "popt"
brew "potrace"
brew "intltool"
brew "ipfs"
brew "nmap"
brew "p7zip"
brew "unrar"
brew "reattach-to-user-namespace"

cask "gpg-suite"
brew "tmux"
brew "hub"
brew "git-secret"
brew "git-lfs"
brew "legit"
brew "aview"
brew "colordiff"
brew "cscope"
brew "ctags"
brew "the_silver_searcher"
brew "parallel"
brew "progress"
brew "awk"
brew "markdown"

brew "pow"
brew "automake"
brew "cmake"
brew "gradle"
brew "maven"
brew "mcrypt"
brew "stow"
brew "llvm"
brew "readline"
brew "xz"

brew "asdf"
brew "crystal"
brew "pyenv"
brew "rbenv"
brew "rbenv-bundler"
brew "rbenv-gemset"
brew "ruby-completion"
brew "rust"
brew "sbt"
brew "scala"
brew "yarn"
brew "nodenv"
brew "elixir"
brew "elixir-build"
brew "awscli"

cask "db-browser-for-sqlite"
cask "neo4j"
brew "sqlite"
brew "freetds"
brew "mysql", restart_service: true, link: false
brew "neo4j", link: false
brew "postgresql", restart_service: true
brew "v8"
cask "sequel-pro-nightly"
cask "postico"
cask "sqlworkbenchj"
cask "valentina-studio"

brew "kafka"
brew "rabbitmq"
brew "redis", restart_service: true

brew "r"
cask "racket"
cask "protege"
brew "jupyter"
brew "sphinx-doc"
brew "stanford-corenlp"
cask "julia"
brew "vowpal-wabbit"

brew "graphviz"
brew "plantuml"
cask "inkscape"
cask "gimp"
cask "omnigraffle"
cask "omnigraffle6"
cask "skitch"
cask "sketch"
cask "drawio"

brew "tesseract"
brew "imagemagick"

cask "vlc"
tap "varenc/ffmpeg", pin: true
brew "varenc/ffmpeg/ffmpeg"
brew "youtube-dl"
brew "gsl"
brew "usbmuxd", args: ["HEAD"]
brew "libimobiledevice", args: ["HEAD"]
brew "libzip"
brew "libiconv"
brew "libpq"
brew "libsodium"
brew "libsoup"
brew "libvpx"
brew "libxml++"
brew "libxml++3"
brew "little-cms"
brew "zlib"
brew "libxml2"
brew "glib"
brew "tidy-html5"

cask "qlimagesize"
cask "qlstephen"
cask "qlvideo"
cask "qlstephen"
cask "quicklookase"
cask "webpquicklook"
