# https://github.com/ptb/mac-setup/blob/develop/mac-setup.command

tap "heroku/brew"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/core"
tap "homebrew/services"
tap "varenc/ffmpeg", pin: true
cask "adoptopenjdk"
cask "xquartz"
cask "suspicious-package"
cask "virtualbox"
cask "visualvm"
cask "platypus"
cask "postman"

brew "cocoapods"
brew "duti"
brew "ios-deploy"
brew "ideviceinstaller"
brew "mas"
brew "pinentry-mac"
cask "homebrew/cask-fonts/font-inconsolata-lgc"

brew "crystal"
brew "python"
brew "awscli"

brew "docker"
brew "docker-compose"
brew "docker-machine"
brew "gdl"

brew "aview"
brew "bash-completion"
brew "bash-git-prompt"
brew "bat"
brew "bundler-completion"
brew "colordiff"
brew "cscope"
brew "ctags"
brew "curl"
brew "curl-openssl"
brew "dnsmasq"
brew "ncdu"
#brew "fasd"
brew "hub"
brew "mosh"
brew "ack"
brew "aspell"
brew "awk"

brew "figlet"
brew "brogue"

brew "libxml2"
brew "glib"

brew "git-secret"
brew "git-lfs"
brew "legit"

brew "automake"
brew "cmake"
brew "gradle"
brew "maven"
brew "mcrypt"
brew "stow"

brew "graphviz"
brew "imagemagick"
brew "youtube-dl"

brew "gsl"
brew "usbmuxd", args: ["HEAD"]
brew "libimobiledevice", args: ["HEAD"]
brew "libzip"
brew "intltool"
brew "ipfs"
brew "irssi"
brew "jq"
brew "jupyter"
brew "kafka"
brew "libiconv"
brew "libpq"
brew "libsodium"
brew "libsoup"
brew "libvpx"
brew "libxml++"
brew "libxml++3"
brew "little-cms"
brew "llvm"
brew "markdown"

cask "db-browser-for-sqlite"
cask "neo4j"
brew "sqlite"
brew "freetds"
brew "mysql", restart_service: true, link: false
brew "neo4j", link: false

brew "nmap"
brew "p7zip"
brew "parallel"
brew "pcre2"
brew "plantuml"
brew "poppler"
brew "popt"
brew "postgresql", restart_service: true
brew "potrace"
brew "pow"
brew "progress"
brew "r"
brew "rabbitmq"
brew "rbenv"
brew "rbenv-bundler"
brew "rbenv-gemset"
brew "reattach-to-user-namespace"
brew "redis", restart_service: true
brew "renameutils"
brew "ruby-completion"
brew "rust"
brew "sbt"
brew "scala"
brew "sphinx-doc"
brew "stanford-corenlp"
brew "tesseract"
brew "the_silver_searcher"
brew "tidy-html5"
brew "tmux"
brew "unrar"
brew "v8"
brew "vim"
brew "vowpal-wabbit"
brew "wget"
brew "wireshark"
brew "yarn"
brew "zlib"
brew "zsh"
brew "zsh-completions"
brew "zsh-git-prompt"
brew "heroku/brew/heroku"
brew "varenc/ffmpeg/ffmpeg"

cask "qlimagesize"
cask "qlstephen"
cask "qlvideo"
cask "qlstephen"
cask "quicklookase"
cask "webpquicklook"

cask "nzbvortex"
cask "mactex"
