#!/usr/bin/sh

# OSX helpers
## Open man pages in Preview
pman() {
  man -t "${1}" | open -f -a /Applications/Preview.app/
}

## Open markdown in MacDown
md() {
  open -a /Applications/MacDown.app/Contents/MacOS/MacDown "${1}"
}

## Open markdown in Mou
mou() {
  open -a /Applications/Mou.app/Contents/MacOS/Mou "${1}"
}

## Open markdown in Mou
git-kraken() {
  open -a /Applications/GitKraken.app/Contents/MacOS/GitKraken "${1}"
}
alias gk=git-kraken
gitkraken() {
  /Applications/GitKraken.app/Contents/MacOS/GitKraken "${1}" &
}

